spring:
  config:
    import:
      - optional:classpath:cibseven-webclient.properties
# H2 Console (optional, for debugging)
  h2:
    console:
      enabled: true
      path: /h2-console

cibseven:
  webclient:
    services:
      basePath: services/v1
    # Engine rest
    engineRest:
      url: http://localhost:8080
    # BPM provider for Enterprise Edition
    # bpm:
    #   provider: org.cibseven.webapp.providers.SevenProviderEE
