
################### Base settings ###################
spring.application.name=company1-department1-api-application1-service
server.servlet.context-path=/department1/application1/v1
spring.cloud.compatibility-verifier.enabled=false

################### JWT settings ###################
spring.config.import=optional:classpath:cibseven-webclient.properties

################### Application DB (primary) ###################
spring.datasource.url=jdbc:h2:file:./app-h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

################### Camunda DB (secondary) ###################
camunda.bpm.datasource.url=jdbc:h2:file:./cibseven-h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
camunda.bpm.datasource.driver-class-name=org.h2.Driver
camunda.bpm.datasource.username=sa
camunda.bpm.datasource.password=

camunda.bpm.database.type=h2
spring.h2.console.enabled=true

############# CIB seven CONFIGURATION #############
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
camunda.bpm.admin-user.firstName=Demo
camunda.bpm.filter.create=All tasks

# ToDo for testing - switch to true here
camunda.bpm.job-execution.enabled=true

camunda.bpm.job-execution.max-wait=30000
camunda.bpm.job-execution.queue-capacity=64
camunda.bpm.job-execution.core-pool-size=4
camunda.bpm.job-execution.max-pool-size=10
camunda.bpm.job-execution.lock-time-in-millis=1800000
camunda.bpm.job-execution.wait-time-in-millis=5000
camunda.bpm.job-execution.max-jobs-per-acquisition=32
camunda.bpm.job-execution.deployment-aware=false


#### CIB 7 Webapp Configuration ####
camunda.bpm.webapp.enabled=true
camunda.bpm.webapp.application-path=/webapp

# Engine rest
cibseven.webclient.engineRest.url=http://localhost:8080
cibseven.webclient.engineRest.path=/department1/application1/v1/engine-rest

cibseven.webclient.services.basePath=services/v1

# BPM provider for Enterprise Edition
cibseven.webclient.bpm.provider=org.cibseven.webapp.providers.SevenProviderEE
