camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  run:
    auth:
      enabled: true
      authentication: composite

spring:
  config:
    import:
      - optional:classpath:cibseven-webclient.properties

cibseven:
  webclient:
    services:
      basePath: /webapp/services/v1
    # Engine rest
    engineRest:
      url: http://localhost:8080
