camunda.bpm:
  history-level: audit
  authorization:
    enabled: true
  filter:
    create: All tasks
  oauth2:
    identity-provider:
      # starter-security idP must be disabled
      enabled: false

# Keycloak Identity Provider Plugin: secure engine REST with OAuth2
rest.security:
  enabled: false
  provider: keycloak
  required-audience: camunda-rest-api

spring:
  jersey:
    application-path: /engine-rest
  config:
    import:
      - optional:classpath:cibseven-webclient.properties

# Spring Boot Security configuration for Keycloak Identity Provider + OAuth2
spring.security:
  oauth2:
    client:
      provider:
        keycloak:
          issuer-uri: <issuerUri>
          jwk-set-uri: <certsUri>
          # set user-name-attribute one of: 
          # - sub                -> default; using keycloak ID as CIB seven user ID
          # - email              -> useEmailAsCamundaUserId=true
          # - preferred_username -> useUsernameAsCamundaUserId=true
          user-name-attribute: preferred_username

logging:
  level:
    root: INFO

# CIB seven Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: <issuerUri>
  keycloakAdminUrl: <adminUri>
  clientId: <clientId>
  clientSecret: <clientSecret>
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  enforceSubgroupsInGroupQuery: true
  administratorGroupName: camunda-admin
  administratorUserId: camunda
  disableSSLCertificateValidation: true

cibseven:
  webclient:
    engineRest:
      url: http://localhost:8080
    authentication:
      tokenValidMinutes: 30
      tokenProlongMinutes: 10
    sso:
      active: true
      endpoints:
        authorization: <authUri>
        token: <tokenUri>
        jwks: <certsUri>
        user: <usersUri>
      clientId: <clientId>
      clientSecret: <clientSecret>
      scopes: openid email profile
      userIdProperty: preferred_username
      userNameProperty: name
      accessTokenToEngineRest: true
    bpm:
     provider: org.cibseven.webapp.providers.SevenProvider
    user:
     provider: org.cibseven.webapp.auth.KeycloakUserProvider

# Metrics & Health
management:
  endpoint.health.probes.enabled: true
  endpoints:
    web.exposure.include: env,health,info,metrics