apiVersion: v1
kind: Service
metadata:
  name: cibseven
  labels:
    app: cibseven
spec:
  selector:
    app: cibseven
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
